import numpy as np
from numpy.typing import NDArray

class _BBox3DUKFBase:
    def __init__(self) -> None: ...
    def init(self, state: NDArray[np.float64], cov: NDArray[np.float64]) -> None: ...
    def predict(self, dt: float) -> None: ...
    def update(self, measurement: NDArray[np.float64]) -> None: ...
    @property
    def state(self) -> NDArray[np.float64]: ...
    @property
    def covariance(self) -> NDArray[np.float64]: ...

class CvBBox3DUKF(_BBox3DUKFBase): ...
class CtrvBBox3DUKF(_BBox3DUKFBase): ...
