import numpy as np
from numpy.typing import NDArray

class CovarianceNotPsd(RuntimeError): ...
class InvalidArgument(ValueError): ...
class NumericalError(RuntimeError): ...

class UkfPosVxyzYawCV:
    N: int
    M: int

    def __init__(
        self, alpha: float = 1e-3, beta: float = 2.0, kappa: float = 0.0
    ) -> None: ...
    def init(self, state: NDArray[np.float64], cov: NDArray[np.float64]) -> None: ...
    def predict(self, dt: float) -> None: ...
    def update(self, measurement: NDArray[np.float64]) -> float: ...
    @property
    def state(self) -> NDArray[np.float64]: ...
    @property
    def covariance(self) -> NDArray[np.float64]: ...
